source: _source
destination: .
markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:day/:title
url: http://chriseppstein.github.com/
multiviews: true
sass: false
haml: true
post_defaults:
  layout: post