source "http://rubygems.org/"

gem "nanoc"
gem "compass"
gem "mongrel"
gem "rack"
gem "mime-types", :require => "mime/types"
gem "rdiscount"
gem "rubypants"
gem "git"
gem "hpricot"
gem "fssm"
gem "nokogiri"
gem "coderay"
gem "serve"
